"""Shared field name constants for reference entities and repository operations."""

# Ordered keys used for string representation and general attribute handling
ORDERED_KEYS = [
    "ref_type",
    "author",
    "title",
    "journal",
    "booktitle",
    "year",
    "editor",
    "volume",
    "number",
    "series",
    "pages",
    "address",
    "month",
    "organization",
    "publisher",
    "edition",
    "howpublished",
    "institution",
    "school",
    "note",
    "type",
    "url",
    "doi",
]

# Column keys for database insert/update parameter mapping
COLUMN_KEYS = [
    "author",
    "title",
    "booktitle",
    "year",
    "url",
    "doi",
    "editor",
    "volume",
    "number",
    "series",
    "pages",
    "address",
    "month",
    "organization",
    "publisher",
    "edition",
    "howpublished",
    "institution",
    "journal",
    "note",
    "school",
    "type",
]
